version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: xd
    ports:
      - 9906:3306
  dbb:    
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    links:
      - db
    ports:
      - "8080:80"
    stdin_open: true
